export const LoginActions = {
    LOGIN: 'LOGIN',
    TRIGGER_LOGIN: 'TRIGGER_LOGIN',
    LOGIN_ERROR: 'ERROR',
    TRIGGER_AUTHORIZE: 'TRIGGER_AUTHORIZE',
    AUTHORIZE_ERROR: 'AUTHORIZE_ERROR',
    TRIGGER_LOGOUT: 'TRIGGER_LOGOUT',
    TRIGGER_SIGNUP: 'TRIGGER_SIGNUP',
    LOGOUT: 'LOGOUT',
    SIGNUP_ERROR: 'SIGNUP_ERROR',
    RESET_ERRORS: 'RESET_ERRORS'
}

export const CourseActions = {
    TRIGGER_GET_ALL: 'TRIGGER_GET_ALL',
    GET_ALL: 'GET_ALL'
}

export const CartActions = {
    TRIGGER_ADD_TO_CART: 'TRIGGER_ADD_TO_CART',
    TRIGGER_REMOVE_FROM_CART: 'TRIGGER_REMOVE_FROM_CART',
    GET_CART: 'GET_CART',
    SET_CART: 'SET_CART',
    UPDATE_CART: 'SET_CART_ALL',
    SET_CART_COURSES: 'SET_CART_COURSES',
    TRIGGER_GET_CART_COURSES: 'TRIGGER_GET_CART_COURSES',
    CLEAR_CART: "CLEAR_CART"
}

export const HistoryActions = {
    ADD_PATH: 'ADD_PATH',
    RESET_PATHS: 'RESET_PATHS'
}

export const PaymentActions = {
    PAYMENT_METHOD: 'PAYMENT_METHOD',
    PAYMENT_DETAILS: 'PAYMENT_DETAILS',
    RESET_PAYMENT: 'RESET_PAYMENT'
}

export const PurchaseActions = {
    PURCHASE_COURSES: "PURCHASE_COURSES",
    SET_PURCHASES: "SET_PURCHASES"
}